on:
  pull_request:
    branches:
      - main

jobs:
  dekekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Setup local.properties
        run: |
          if [ ! -f "./local.properties" ]; then
          echo "sdk.dir=${{ secrets.ANDROID_SDK_PATH }}" > local.properties
          fi

      - name: Build and run detekt
        run: ./gradlew detekt
